{% set name = "py4xs" %}
{% set version = "2019.6.28.0" %}
{% set sha256 = "75c51a39618f52492a3b3b57465a4f20d1d56005deb53028cb051b8d4e6fbbd7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - fabio
    - matplotlib
    - numpy
    - pillow
    - scipy

test:
  imports:
    - py4xs

about:
  home: https://github.com/NSLS-II-LIX/py4xs
  license: MIT
  license_file: LICENSE.txt
  summary: py4xs - a python package for processing x-ray scattering data
